# Site settings
title: 百里闪闪文化
email: blss@mqtcun.com
url: https://bailishanshan.github.io
description: "用科学的方法加快你探索世界的速度!"
meta_author: Yixuan Li

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: BDD962 #80B3FF
  primary-rgb: 24,288,156" #"128,179,255"
  secondary: 2c3e50
  secondary-dark:  233140 #A2122F


# Footer settings
footer:
  copyright: 百里闪闪文化
  location: 地址
  social: 联系我们
  credits: <a href="http://www.macundexiatian.com">马村的夏天</a>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/blss1/?ref=bookmarks
  - title: weibo
    url: http://weibo.com/bailishanshan
  - title: github
    url: https://github.com/bailishanshan

# Postal address (add as many lines as necessary)
address:
  - line: 北京市 昌平区 龙德紫金广场
  - line: 3楼415 102218

# Credits content
credits: '马村的夏天, 让记忆更简单!'

# Build settings
markdown: kramdown
permalink: pretty
